### ISSUE TITLE
Missing Git Branch Symbol

### ISSUE THREAD

**Issue by mtslzr** [JetBrains/JetBrainsMono#9] opened 2020-01-15 17:27 UTC
When using with iTerm and Starship prompt, the git branch icon appears broken.

JetBrains Mono:
![image](https://user-images.githubusercontent.com/6003715/72456201-301a3c00-3792-11ea-8019-568f06b865ce.png)

Fira Code:
![image](https://user-images.githubusercontent.com/6003715/72456223-3b6d6780-3792-11ea-9b01-6a0c59769bf0.png)

**Comment by emanguy** [comment] 2020-01-16 02:34
This is a duplicate of #2, as this requires a font with powerline symbols/extra glyphs. Try the version on the related pull request.

**Comment by philippnurullin** [comment] 2020-01-22 16:33
@mtslzr Will be included in v 1.0.2

**Closed** 2020-01-27 10:24 UTC
Labels: enhancement
