### ISSUE TITLE
`===` ligature lacks symmetry

### ISSUE THREAD

**Issue by user11681** [JetBrains/JetBrainsMono#418] opened 2021-03-06 03:15 UTC
At some font sizes, the distances between the middle line and the other lines in `===` are not the same:
![Screenshot_20210306_030554](https://user-images.githubusercontent.com/44427720/110192935-f1799200-7e28-11eb-9943-9b2215d24eee.png)
This screenshot was taken with a size of 24 in whatever unit that IntelliJ IDEA uses (pt?), although I use 14, which has the same problem.

Other sizes, 11 and 15 for example, look fine for me.

I am unsure about the version of JetBrains Mono that I am using, but my IntelliJ IDEA version is 2020.3.2 build #IC-203.7148.57.

**Comment by TheMadHau5** [comment] 2021-03-06 07:02
This seems to be a hinting issue, although I'm not quite sure

**Comment by trygveaa** [comment] 2021-03-06 08:11
Duplicate of #25.

**Closed** 2021-03-30 11:11 UTC
Labels: duplicate
