### ISSUE TITLE
VSCode - Integrated Terminal issues with Powerline

### ISSUE THREAD

**Issue by gsbhasin123** [JetBrains/JetBrainsMono#54] opened 2020-01-18 00:39 UTC
Strange. Im using the `agnoster` oh my zsh theme which works fine in the Tilix emulator. vscode's interegated terminal is broken though
![image](https://user-images.githubusercontent.com/48339289/72655144-e83d1580-3947-11ea-9186-1ad54fea0812.png)
Please fix

**Comment by damieng** [comment] 2020-01-18 07:03
Duplicate of #2

**Comment by ryoppippi** [comment] 2020-01-18 14:22
Refer this https://github.com/JetBrains/JetBrainsMono/issues/2#issuecomment-575902642

**Comment by gsbhasin123** [comment] 2020-01-18 15:25
@ryoppippi  @damieng  as i'm trying to say, it works in my normal terminal:
![image](https://user-images.githubusercontent.com/48339289/72666084-ab166900-39c3-11ea-94fb-244f9aaaddc4.png)

The problem is only with my Vscode terminal, does your PR fix that?

**Comment by damieng** [comment] 2020-01-18 16:11
One of those terminals is falling back to another font for the missing glyphs the other is not.

**Comment by gsbhasin123** [comment] 2020-01-18 17:10
Alright, please fix

**Comment by ryoppippi** [comment] 2020-01-19 06:27
It looks fine on my VScode

**Comment by gsbhasin123** [comment] 2020-01-19 20:17
@ryoppippi are you using Powerline prompt?

**Comment by ryoppippi** [comment] 2020-01-20 02:01
yeah
<img width="341" alt="スクリーンショット 2020-01-20 11 00 52" src="https://user-images.githubusercontent.com/1560508/72693437-23239100-3b74-11ea-8988-193a893a3fc4.png">

**Comment by aaronbell** [comment] 2020-01-20 05:50
@ryoppippi As the font doesn't include powerline symbols, you must have some fallback set up in your version.

**Comment by philippnurullin** [comment] 2020-01-24 15:58
@gsbhasin123 Powerline symbols added in v 1.0.2. Feel free to try it.

**Comment by gsbhasin123** [comment] 2020-01-24 17:14
Great!

**Closed** 2020-01-25 00:07 UTC
