### ISSUE TITLE
diacritics alignment problems

### ISSUE THREAD

**Issue by kchibisov** [JetBrains/JetBrainsMono#228] opened 2020-04-30 05:45 UTC
version of the font: 1.0.**6**

tested on 1.0.5 and it was broken in +- the same way.

It seems like diacritics are still has alignment problems. The following file contains a good test case to check their alignment [sample.txt](https://github.com/JetBrains/JetBrainsMono/files/4556339/sample.txt). On the last lines of this file it's way more noticeable, since those chars are inside of the glyphs.

The issue could be observed in [alacritty](https://github.com/alacritty/alacritty) and Firefox 75 on linux. note, Alacritty doesn't perform font shaping, so diacritics weren't combined with anything else (noticeable on Fira Code example, since it renders them a bit better than Firefox)

In alacritty part of this file looks like this:

![jetbrains-alacritty](https://user-images.githubusercontent.com/27620401/80675907-4d171880-8abe-11ea-9af7-b0a715edae62.png)

In Firefox it looks like this(tested by simply pasting in https://godbolt.org/

![jetbrains](https://user-images.githubusercontent.com/27620401/80675932-5acc9e00-8abe-11ea-8790-02a34789e880.png)

On the other hand, Fira Code seems to render fine in the mentioned programs.

alacritty

![fira-alacritty](https://user-images.githubusercontent.com/27620401/80676015-82bc0180-8abe-11ea-8d7f-77a23d378f3b.png)

Firefox

![fira](https://user-images.githubusercontent.com/27620401/80676059-96676800-8abe-11ea-8937-55eaf1cc3267.png)

**Comment by philippnurullin** [comment] 2020-04-30 07:55
This diacritics look looks it was auto generated from existing glyphs. 
In your example the `â` is generated from 2 separete glyphs on the go in editor. For example, there are two glyphs in sequence `uni0061` (a) + `uni0302` (circumflex). And by adjusting the placement of circumflex in its place this "auto" glyph can be generated like in your example. In JetBrains Mono this glyph is made like one `â`, so this test example is not representing the actual placement of the diaritics in JetBrains Mono.
This is a list of all diacritics symbols currently supported: `ijÀÁÂÃÄÅÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞàáâãäåçèéêëìíîïðñòóôõöøùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦĨĩĪīĬĭĮįİĴĵĶķĹĺĻļĽľĿŀŁłŃńŅņŇňŉŌōŎŏŐőŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžƏƒƠơƯưǦǧǪǫǴǵǼǽǾǿȘșȚțЁЃЇЌЎЙйёѓіїјќўẀẁẂẃẄẅẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘộỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹ`

But, this approach to make diacritics is interesting. I will look at it. Do you know where this constructed diacritics is used?

**Comment by kchibisov** [comment] 2020-04-30 08:21
>In your example the â is generated from 2 separete glyphs on the go in editor. 

Hm, that's interested, but I know for sure that alacritty(terminal emulator) can't do that at all, it just asks FreeType to get glyph for exactly one char at the time and don't shape them at all. Could you elaborate on what `editor` is here, just curious? Are you talking about that they are separate from the glyphs and text editing program (e.g. Firefox) then combines them? If so, yes, they are separate from the glyphs and combined later, but naturally and not by editor, since such glyphs tend to have special metrics (negative offsets, etc), so it's font responsibility to position them properly. Some fonts have wrong metrics for them and you can see them separate, like `DejaVu Sans Mono`. e.g. https://github.com/alacritty/alacritty/issues/2620#issuecomment-583786216

>But, this approach to make diacritics is interesting. I will look at it. Do you know where this constructed diacritics is used?

Idk, I feel like they just happen to be seen from time to time. We've seen them here https://github.com/alacritty/alacritty/issues/1420 and https://github.com/alacritty/alacritty/issues/2620

**Comment by philippnurullin** [comment] 2020-04-30 08:36
> but I know for sure that alacritty(terminal emulator) can't do that at all

I think it can. The logic of this thing is that's just two glyphs, one after another. The diacritic mark have just negative spacing, so it can be placed correctly. This is possible in every text editor. 
The problem is that examples in *sample.txt* are all like this. So it produces the fals results because instead reaching for correct glyphs it's trying to recreate them. I'm sure this technique is made on purpose but this needs to be explored further.

**Comment by kchibisov** [comment] 2020-04-30 08:41
>I think it can. The logic of this thing is that's just two glyphs, one after another. The diacritic mark have just negative spacing, so it can be placed correctly. This is possible in every text editor.

>>but naturally and not by editor, since such glyphs tend to have special metrics (negative offsets, etc), so it's font responsibility to position them properly.

Yeah, as  I said. If font have wrong metrics for them, user is out of luck.

**Comment by Mouvedia** [comment] 2020-10-21 19:24
2.200 doesn't fix this issue in Alacritty. @philippnurullin please reopen.

**Comment by philippnurullin** [comment] 2020-10-22 08:10
Hi @Mouvedia . Please make sure that you removed the the old font from OS fist and please provide screenshots with problem. The exact copy of the code/text in editable format will be nice to.

**Comment by kchibisov** [comment] 2020-11-15 10:16
@philippnurullin I've rechecked this issue, and it seems like you've added some diacritics, however as far as I can see the `left` position for them is positive, thus they are rendered to the right of the glyph, however fonts like Hack/Fira Mono are using negative `left` for them, so they are placed naturally, also only certain diacritics were added and not all from the `sample.txt`

However JetBrains mono seems to have a good example of diacritics and it's `\u{336}`, which has left `-10`(for 10pt size) and looks the following.

![picture](https://user-images.githubusercontent.com/27620401/99182181-70e13980-2744-11eb-9ce6-5b2bc598bddb.png)

Unlike some other glyphs from the mentioned 'sample.txt' in the issue.

![picture](https://user-images.githubusercontent.com/27620401/99182195-8c4c4480-2744-11eb-9ef7-954060539ebd.png)


For the test the font version was `v2.210`.

**Comment by philippnurullin** [comment] 2020-12-21 16:09
@kchibisov Please test latest push. It took more time that expected, but all the mark that are currently in the font placed with negative LSB. Should work now.

**Comment by Mouvedia** [comment] 2020-12-21 16:38
The ones that I care about are fixed. Thanks!

Here's a subset of the sample list of the ones that aren't:
```
a̅b̅c̅
a̍b̍c̍
a̎b̎c̎
a̐b̐c̐
ȃb̑c̑
a̓b̓c̓
a̔b̔c̔
a̕b̕c̕
a̖b̖c̖
a̗b̗c̗
a̘b̘c̘
a̙b̙c̙
a̚b̚c̚
a̜b̜c̜
a̝b̝c̝
a̞b̞c̞
a̟b̟c̟
a̠b̠c̠
a̡b̡c̡
a̢b̢c̢
a̤b̤c̤
a̩b̩c̩
a̪b̪c̪
a̫b̫c̫
a̬b̬c̬
a̭b̭c̭
a̮b̮c̮
a̯b̯c̯
a̰b̰c̰
a̱ḇc̱
a̲b̲c̲
a̳b̳c̳
a̴b̴c̴
a̵b̵c̵
a̹b̹c̹
a̺b̺c̺
a̻b̻c̻
a̼b̼c̼
a̽b̽c̽
a̾b̾c̾
a̿b̿c̿
a̓b̓c̓
a͘b͘c͘
a͜b͜c͜
a͝b͝c͝
a͞b͞c͞
a͟b͟c͟
a͠b͠c͠
a͡b͡c͡
a͢b͢c͢
```

**Comment by philippnurullin** [comment] 2020-12-28 14:54
The JetBrains Mono is not supporting the all diacritics presented in the sample. All the diacritics it support should work fine. I'm not sure on the popularity of what's left, so i will wait for the request to add it.
Closing this issue because general problem is solved.

**Closed by philippnurullin** 2020-12-28 14:54 UTC
Labels: unicode request
