### ISSUE TITLE
Is there a reason for `|` is diagonally a bit?

### ISSUE THREAD

**Issue by tyankatsu0105** [JetBrains/JetBrainsMono#157] opened 2020-02-21 01:40 UTC
Hi! I'm one of the JetBrainsMono's fan.
This font is soooooooo cool. Thanks to all contributors.

Btw, I have a question.
I notice that `|` is diagonally a bit.
I want to know the reason!!

Thanks.

**Comment by philippnurullin** [comment] 2020-02-21 07:29
@tyankatsu0105 Hi, glad to hear that you like the font. Can you send me the screenshot with `|`?

**Comment by tyankatsu0105** [comment] 2020-02-21 07:43
@philippnurullin 
Sure! Here you are.
![Uploading スクリーンショット 2020-02-21 16.32.32.png…]()

I use `JetBrainsMono-Regular` with VSCode.
To be honest, I don't know typeface very much.
So, could you teach me if I just don't know about it?

**Comment by philippnurullin** [comment] 2020-02-21 07:57
@tyankatsu0105 It's hart to tell because there is not much context but it looks like the `|` is set in Italic. Please send a bigger image with some code, i will be able to understand the context better.

**Comment by tyankatsu0105** [comment] 2020-02-21 08:34
@philippnurullin
Oh, I understand! What I saw is italic font, right?
Umm... If this is caused by editor, I can't change settings...
Anyway, I able to know that finally. Thanks!

**Comment by philippnurullin** [comment] 2020-02-21 08:47
@tyankatsu0105 _To be sure that this is Italic i need to see the bigger chunk of code_. But il looks like it is.

**Comment by tyankatsu0105** [comment] 2020-02-25 00:40
@philippnurullin 
I just checked my editor's settings!

## STEP 1
Write a code. Example:
```js
const foo = 'a' || 'b';
```

## STEP 2
Open Command Palette.
Then, input this:
```bash
>Developer Inspect Editor Tokens and Scopes
```

## STEP 3
Hover `||` on `const foo = 'a' || 'b';`
<img width="593" alt="スクリーンショット 2020-02-25 9 20 14" src="https://user-images.githubusercontent.com/28397593/75203411-57aced00-57b1-11ea-82f1-899273e5a0fd.png">

As you said, the font style is `italic`!!!
So, I changed settings.

```json
"editor.tokenColorCustomizations": {
      "textMateRules": [
        {
          "scope": [
            "keyword.operator.logical"
          ],
          "settings": {
            "fontStyle": ""
          }
        }
      ]
    }
```

Finally, I get what I want :)
<img width="167" alt="スクリーンショット 2020-02-25 9 38 54" src="https://user-images.githubusercontent.com/28397593/75203904-c76fa780-57b2-11ea-9bc0-f22764853290.png">

**Comment by philippnurullin** [comment] 2020-02-27 07:52
@tyankatsu0105 Glad to hear thats everything works for you! I will close this issue because the problem is solved.

**Closed by philippnurullin** 2020-02-27 07:52 UTC
