### ISSUE TITLE
Font not returned by Windows in list of monospaced fonts

### ISSUE THREAD

**Issue by WmHBlair** [JetBrains/JetBrainsMono#69] opened 2020-01-20 18:54 UTC
I have many monospaced "program editing" fonts installed on Windows (10). In various program editor applications that I have installed, JetBrainsMono is exhibited as a choice in the resulting list (of what are obviously "all" monospaced fonts that are on the system). But JetBrainsMono appears in none of these applications; it is as if Windows is not aware that it is a monospaced font. In applications that list all installed fonts, it does appear as a selection, just not in applications that are intended to use only monospaced fonts. I have obtained the C source code of one (non-free and non-open source) editor application I use that calls the EnumFontFamiliesEx() Windows function, but I don't want to post it openly here (I could probably get permission to do so, but have not asked). The key parameters to that function specify the following:

Weight: DONTCARE
OutPrecision: OUT_DEFAULT_PRECIS
ClipPrecision: CLIP_DEFAULT_PRECIS
Quality: DEFAULT_QUALITY
PitchAndFamily: FF_MODERN (i.e., supposedly monospace only)
CharSet: DEFAULT_CHARSET 

The vendor says any font returned by Windows by that API will be presented in the exhibited list. Are any of those wrong (i.e., do not match the attributes of JetBrainsMono)?

**Comment by IgorEisberg** [comment] 2020-01-20 20:35
Duplicate of #4

**Comment by philippnurullin** [comment] 2020-01-22 08:09
The 1.0.1 is fixing this problem. Please download the updated version.

**Closed by philippnurullin** 2020-01-22 08:09 UTC

**Comment by WmHBlair** [comment] 2020-01-22 23:55
![Problem 1-A](https://user-images.githubusercontent.com/34389465/72944961-24091e00-3d40-11ea-8091-d8dd7c701eb9.jpeg)

All 1.0.1 versions of the TTF files are unacceptable to Windows 10. The message issued for each is: "The file XXXX.ttf does not appear to be a valid font."

**Comment by philippnurullin** [comment] 2020-01-27 14:59
@WmHBlair is this problem still relevant for v1.0.2? Ia so i will create the separate issue.

**Comment by WmHBlair** [comment] 2020-02-01 18:17
The original problem I reported (not properly marked as a monospaced font
to Windows) has been fixed by 1.0.2. I have another problem, a very unusual
one, for which I will open another problem. Thanks for the fix for this one.
