### ISSUE TITLE
Size of colored text wrong after upgrade to 1.0.6

### ISSUE THREAD

**Issue by vianpl** [JetBrains/JetBrainsMono#227] opened 2020-04-29 13:17 UTC
I went back to 1.0.5 and can't reproduce it there, here's a screenshot of what I see with 1.0.6 (white text is OK colored text shrunk):

![font-color](https://user-images.githubusercontent.com/3706469/80600155-4344d500-8a2c-11ea-80eb-b28f62e6d01b.png)

**Comment by vianpl** [comment] 2020-04-29 13:18
BTW, thanks for the amazing work!

**Comment by philippnurullin** [comment] 2020-04-29 13:25
The colored text is set in other font not in JetBrains Mono. 
Seems like the problem of Editor you using.

Try to remove the old font, restart, install the new version. Let me know if this helps.

**Comment by philippnurullin** [comment] 2020-04-29 13:36
The font used for coloured pieces is **Source Code Pro**. Maybe it will help locate the problem. 

If instruction above won't help please send the OS, Editor (with its version). We will try to reproduce.

**Comment by vianpl** [comment] 2020-04-30 08:55
Uninstalled-rebooted-installed as suggested without luck.

My system is openSUSE Tumbleweed, Gnome Wayland+kitty terminal emulator.

**Comment by vianpl** [comment] 2020-04-30 09:23
Has you said earlier the alternative font selected is SourceCodePro, as seen here:

```
nico@linux-9qgx:~/c/u-boot> kitty --debug-font-fallback # JetBrainsMono v1.0.5
[121 11:16:11.439833] Preloaded font faces:
[121 11:16:11.439857] normal face: /home/nico/.fonts/JetBrainsMono-Regular.ttf:0
[121 11:16:11.439866] bold face: /home/nico/.fonts/JetBrainsMono-Bold.ttf:0
[121 11:16:11.439874] italic face: /home/nico/.fonts/JetBrainsMono-Italic.ttf:0
[121 11:16:11.439881] bi face: /home/nico/.fonts/JetBrainsMono-Bold-Italic.ttf:0

nico@linux-9qgx:~/c/u-boot> kitty --debug-font-fallback # JetBrainsMono v1.0.6
[121 11:17:02.491847] Preloaded font faces:
[121 11:17:02.491873] normal face: /home/nico/.fonts/JetBrainsMono-Regular.ttf:0
[121 11:17:02.491881] bold face: /usr/share/fonts/texlive-sourcecodepro/SourceCodePro-Regular.otf:0
[121 11:17:02.491892] italic face: /home/nico/.fonts/JetBrainsMono-Italic.ttf:0
[121 11:17:02.491899] bi face: /usr/share/fonts/texlive-sourcecodepro/SourceCodePro-Regular.otf:0
```

**Comment by philippnurullin** [comment] 2020-04-30 09:34
Looks interesting. Tanks for sharing!

**Comment by trygveaa** [comment] 2020-04-30 11:53
This is caused by the Bold and ExtraBold styles in version 1.0.6 containing glyphs of multiple different sizes.

You can see this by querying with fontconfig:

```
$ for f in JetBrainsMono-1.0.5/ttf/JetBrainsMono*; do echo $f; fc-query $f | grep spacing; done
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Bold-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Bold.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-ExtraBold-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-ExtraBold.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Medium-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Medium.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Bold-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Bold.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-ExtraBold-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-ExtraBold.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Medium-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Medium.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMonoNL-Regular.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.5/ttf/JetBrainsMono-Regular.ttf
	spacing: 100(i)(s)

$ for f in JetBrainsMono-1.0.6/ttf/JetBrainsMono*; do echo $f; fc-query $f | grep spacing; done
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Bold-Italic.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Bold.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMono-ExtraBold-Italic.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMono-ExtraBold.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Medium-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Medium.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Bold-Italic.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Bold.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-ExtraBold-Italic.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-ExtraBold.ttf
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Medium-Italic.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Medium.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMonoNL-Regular.ttf
	spacing: 100(i)(s)
JetBrainsMono-1.0.6/ttf/JetBrainsMono-Regular.ttf
	spacing: 100(i)(s)
```

So the spacing property is only set for regular and medium styles. According to https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font:

> Note that the spacing property is calculated by fontconfig based on actual glyph widths in the font.

As far as I know, the spacing property will not be set if the font has glyphs of various sizes.

**Comment by philippnurullin** [comment] 2020-04-30 12:07
@trygveaa Thanks a lot!

**Comment by philippnurullin** [comment] 2020-04-30 12:11
The problem is in the `uni1EB6`, `Ặ`. This is a letter from Vietnamese alphabet. Its slightly wider than standard width. This will be fixed with next update.

**Closed** 2020-07-13 09:37 UTC
Labels: bug
