### ISSUE TITLE
Some ligatures do not works

### ISSUE THREAD

**Issue by pioz** [JetBrains/JetBrainsMono#367] opened 2020-11-16 15:22 UTC
I'm using Sublime Text and when I open a ruby source file `.rb` some ligatures do not work (for example `->` or `~~>`). 
If I change the file in "Plain Text" all ligatures work.
This behavior exists also with js files.
Any idea to enable all ligatures also in `js` and `rb` files?

**Comment by kenmcd** [comment] 2020-11-17 23:10
This is an issue which must be fixed in the Sublime Text package files for each language.
The limited ligatures documentation here: https://www.sublimetext.com/docs/3/ligatures.html 
mentions "tokens" which affect the creation of the ligatures.

From what I can tell the `JavaScript.sublime-package` file must be modified to fix this for JavaScript.
But there is no documentation I have found which really explains this.
Same with the `Ruby.sublime-package` file for Ruby.

Here is a forum post about a ligatures issue with Clojure and Fira Code:
https://forum.sublimetext.com/t/some-fira-code-ligatures-not-working-in-clojure-syntax/33930 
There was also another post about a ligatures issue with the PragmataPro font.
So it is not the fonts that is the issue, it is Sublime Text.

Note that if you change the Syntax setting to HTML then those ligatures will work.
Same with selecting Clojure, or Haskell, but you will see different ligatures will then work.
It is the code in the packages files which is making it work properly.

It appears JetBrains Mono is working fine, and the issue is in Sublime Text.
So someone with knowledge of Sublime Text syntax package files must fix this.
You can file Packages Issues here: https://github.com/sublimehq/Packages

**Comment by philippnurullin** [comment] 2020-12-02 10:47
Thanks @kenmcd for clearing that up.

**Closed by philippnurullin** 2020-12-02 10:47 UTC
Labels: invalid
