### ISSUE TITLE
The different display between IDEs developed by JetBrains and VSCode  

### ISSUE THREAD

**Issue by clzoc** [JetBrains/JetBrainsMono#495] opened 2021-09-25 12:03 UTC
system: windows10 21H1.
cpu: AMD Ryzen 4800H.

I am grateful for authors of this project, it is actually a wonderful work. Usually, i use this font with VSCode and i am satisfied with the display. The pictures below show my settings and visual effect. (Note that it works well when only one kind of font weight had been installed in my windows system. If i install more than one kind of font weight, the width of the font become narrower and the glyph become more curved)
![Snipaste_2021-09-25_19-11-25](https://user-images.githubusercontent.com/62627722/134769620-d3eb48e1-4d9a-4659-ae90-2a5cd4e1110f.jpg)
![Snipaste_2021-09-25_19-06-22](https://user-images.githubusercontent.com/62627722/134769666-f9e8ecf8-7576-43db-9188-cec1299d7425.jpg)

Recently, i have used four IDEs developed by JetBrains include IDEA, CLion, GoLand and PyCharm. But their display with JetBrains Mono is different from VSCode.
![Snipaste_2021-09-25_18-59-17](https://user-images.githubusercontent.com/62627722/134770215-25985a6e-cd6a-440b-82ce-b2690b4c6b10.jpg)

I tried to reproduce the same visual effect in the IDEs developed by JetBrains but i failed. Almost, i intended to give up.  However, few days ago, i installed JetBrains Mono NL Thin in my windows system and selected it as the font of editor, the display was really what i want.  The width of the font become wider and the glyph become more straight. (According to my experiment,  only NL and Thin font succeed，others failed)
![Snipaste_2021-09-25_18-58-51](https://user-images.githubusercontent.com/62627722/134770597-d8773537-9f5c-49c7-beb3-0c55553ed36b.jpg)

I am not a advanced developer, so i am asking for help about my problem. I want to know the reason which is responsible for the different display.

Thank you.

**Comment by CodeCrazy-ywt** [comment] 2021-09-25 14:10
Is your font size in your JetBrains IDEs same as that in VSCode?

**Comment by alexeyten** [comment] 2021-09-25 15:31
Could be related to (or duplicate of) #38

**Comment by clzoc** [comment] 2021-09-25 23:19
> Is your font size in your JetBrains IDEs same as that in VSCode?

Yes, the font size in both of them is 16.

**Comment by clzoc** [comment] 2021-09-26 00:05
> Could be related to (or duplicate of) #38
> 
> Also it’s worth to see this comment [#142 (comment)](https://github.com/JetBrains/JetBrainsMono/issues/142#issue-563844137)

Thanks for your suggestion. I have followed the instruction of issue 142 by removing the bundled JetBrains Mono fonts manually and reinstalling the new version in OS but it seems that i failed. In fact, i prefer JetBrains Mono with wider word spacing and more straight glyph. In VSCode, the font becomes wider and more straight by installing only one kind of font weight in OS and setting "editor.fontWeight" to "bold". However, in JetBrains IDEs, only "JetBrainsMonoNL-Thin" the single font works as i expect, others such as "JetBrainsMonoNL-Regular", "JetBrainsMono-Thin" and "JetBrainsMono-Light" keep narrower word spacing and more curved glyph.

**Comment by clzoc** [comment] 2021-09-26 00:15
![Snipaste_2021-09-26_08-14-18](https://user-images.githubusercontent.com/62627722/134788970-7e0a2d45-7c64-4843-a863-04b225d98055.jpg)

**Comment by philippnurullin** [comment] 2021-09-27 08:15
Hi @clzoc 

When you installing just one file/weight what is exact file you installing?

If you installing only the Regular weight and adding the `"editor.fontWeight": "bold"` this may deform letters.
I'm not 100% sure how VSCode dealing with the situation but usually it is this:
- IDE ses that there is no **Bold** font for this font-family is installed.
- And it applies *Synthetik Bold*. It is a straight forward algorithm and as a result a lot of letter details vanishing in the process and the contour becomes different/bad if compared to drawn **Bold** weight.
And you seem to like how it looks. Which is absolutely fine.
To test this please send an image with font without `"editor.fontWeight": "bold"` applied.

Regarding the comparison of font rendering in VSCode and JB IDE. The font rendering is just different in different IDE. In the Thin version of the font space between letters usually increased because of the more thin strokes. And that creates more spacious rhythm that you like. 
We have a ticket about manual letter spacing. You con vote on it here → https://youtrack.jetbrains.com/issue/IDEA-131850

**Comment by clzoc** [comment] 2021-09-27 09:39
> Hi @clzoc
> 
> When you installing just one file/weight what is exact file you installing?
> 
> If you installing only the Regular weight and adding the `"editor.fontWeight": "bold"` this may deform letters.
> I'm not 100% sure how VSCode dealing with the situation but usually it is this:
> 
> * IDE ses that there is no **Bold** font for this font-family is installed.
> * And it applies _Synthetik Bold_. It is a straight forward algorithm and as a result a lot of letter details vanishing in the process and the contour becomes different/bad if compared to drawn **Bold** weight.
>   And you seem to like how it looks. Which is absolutely fine.
>   To test this please send an image with font without `"editor.fontWeight": "bold"` applied.
> 
> Regarding the comparison of font rendering in VSCode and JB IDE. The font rendering is just different in different IDE. In the Thin version of the font space between letters usually increased because of the more thin strokes. And that creates more spacious rhythm that you like.
> We have a ticket about manual letter spacing. You con vote on it here → https://youtrack.jetbrains.com/issue/IDEA-131850

Thanks for your patience and professional answer. Now, i am convinced that "Synthetik Bold" is the reason of my question. What i hava installed in my PC is "JetBrainsMono-Light (version is 2.242)". 

Without "editor.fontWeight": "bold" applied, the font rendering looks like the picture below.
![Snipaste_2021-09-27_17-14-00](https://user-images.githubusercontent.com/62627722/134882797-375333ad-5535-47c3-9055-18ee4ca7bc89.jpg)
In contrast, with "editor.fontWeight": "bold" applied, it looks like:
![Snipaste_2021-09-27_17-13-45](https://user-images.githubusercontent.com/62627722/134883178-7fcb8bed-62e5-444d-9f7e-f3b312711842.jpg)

It seems that what i expect is a result of a lot of letter details vanishing, oh such a sad story. Finally, i would like to express my gratefulness to you again, byebye.

**Comment by clzoc** [comment] 2021-09-27 10:13
Just one more question. I can't find enough information about the detail of "Synthetik Bold" algorithm. Is it possible for me to apply "Synthetik Bold" algorithm in some fonts manually under the assistance of software such as FontForge?

**Comment by CodeCrazy-ywt** [comment] 2021-09-27 11:30
Maybe syntheti**c** not syntheti*k*?

**Comment by clzoc** [comment] 2021-09-27 11:59
> Maybe syntheti**c** not syntheti_k_?

much likely

**Comment by philippnurullin** [comment] 2021-09-28 08:42
I wasn't referring to a particular **The algorithm**. 
But logic behind it will be something like this. Expand all the contours to +x. I suggest ask the VSCode team. Maybe someone can tell you in details how it works.
Or maybe there is some free basic script for the FontForge that will modify the contour.

**Closed by philippnurullin** 2021-09-28 08:42 UTC
