### ISSUE TITLE
ß and ſ must follow the f design in italic

### ISSUE THREAD

**Issue by thlinard** [JetBrains/JetBrainsMono#24] opened 2020-01-16 07:58 UTC
The long s (ſ) must follow the design of the f in italic: if the f gains a descender, so does the ſ.

ß is a ligature ſ + s, so it also needs a descender in italic.

**Comment by philippnurullin** [comment] 2020-01-17 08:18
Thanks! Will be added asap.

**Comment by philippnurullin** [comment] 2020-01-22 08:34
Fixed in 1.0.1

**Comment by thlinard** [comment] 2020-10-21 18:25
Hi @philippnurullin 
Please reopen: the correction was reverted for 2.000

**Comment by philippnurullin** [comment] 2020-10-22 08:06
Hi @thlinard Thanks for report. Look like the problem is only with the `ſ`. 
Will fix in the next update/

**Comment by thlinard** [comment] 2020-10-22 15:18
> Hi @thlinard Thanks for report. Look like the problem is only with the `ſ`.
> Will fix in the next update/

Yes, the ß is fine. Thank you!

**Comment by philippnurullin** [comment] 2020-11-09 16:48
Fixed in https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.210
Sorry forgot to mention it in the commit.

**Closed by philippnurullin** 2020-11-09 16:48 UTC
Labels: bug
