### ISSUE TITLE
Inconsistent shape of opening and closing single quote (in v2.302)

### ISSUE THREAD

**Issue by YVVT** [JetBrains/JetBrainsMono#575] opened 2022-11-09 10:43 UTC
![image](https://user-images.githubusercontent.com/62426149/200809504-3deab70b-7f5e-47cf-b185-19298349f87c.png)

**Comment by cmarincia** [comment] 2022-11-25 19:53
Hey!
Can you give more details about how to reproduce this issue?
I tried on VS Code and I couldn't reproduce it. Maybe it's a problem with the software you are using?

**Comment by YtotheWT** [comment] 2022-11-26 07:06
1. Make sure that the version of your font is v2.302.
2. Type `‘’` (An opening single quote mark and a closing single quote mark) in any text editor.
3. To better see the effect, you can zoom in.

**Comment by atauzki** [comment] 2022-11-26 08:32
I saw the same issue in 2.302. the right quote is inconsistent with the left one.
![image](https://user-images.githubusercontent.com/19769843/204079872-aa5eb086-5a26-4402-a6ca-04baad474366.png)

**Comment by cmarincia** [comment] 2022-11-26 10:43
I tested again, I used the wrong char when testing.

![image](https://user-images.githubusercontent.com/35623921/204084726-54f16a39-31d9-4738-b026-297f09f3a81c.png)

https://www.compart.com/en/unicode/U+2018
https://www.compart.com/en/unicode/U+2019

**Closed** 2022-12-12 11:04 UTC
