### ISSUE TITLE
Line drawing characters overlap creating visual noise

### ISSUE THREAD

**Issue by blargh-sys** [JetBrains/JetBrainsMono#484] opened 2021-08-23 07:51 UTC
Line drawing characters overlap creating a ridge that is very distracting.

![2021-08-23_09-37](https://user-images.githubusercontent.com/62667323/130409191-cae2dd1f-b114-44a2-ba96-939117de968b.png)

This is from alacritty running in Ubuntu 20.04.3, but the same issue appears in SublimeText 4113.

**Comment by philippnurullin** [comment] 2021-10-05 11:06
Hi @blargh-sys . The problem is that the if the lines are shorted in some cases it creates small gaps instead. See https://github.com/JetBrains/JetBrainsMono/issues/84 https://github.com/JetBrains/JetBrainsMono/issues/165
This is caused by the different rasterization process of the font in different IDE / Terminals. 

So to have small overlapping in some cases is a lesser evil that have gaps.

I don't see a better way to address this problem. So i'm closing the issue.

**Closed by philippnurullin** 2021-10-05 11:06 UTC
