### ISSUE TITLE
Powerline Symbols not working

### ISSUE THREAD

**Issue by OmegaRogue** [JetBrains/JetBrainsMono#221] opened 2020-04-25 14:08 UTC
In VSCode, Windows Terminal and Windows Character Map the Powerline symbols are shown as thin underscores
![image](https://user-images.githubusercontent.com/24958536/80281899-ac67d800-870e-11ea-8c18-a895d3899a1f.png)
![image](https://user-images.githubusercontent.com/24958536/80281909-bee21180-870e-11ea-8cf7-a060ab95a3c3.png)
![image](https://user-images.githubusercontent.com/24958536/80281915-c4d7f280-870e-11ea-993b-a7d4b1ea4fe1.png)
the character icon in the character map is working, but highlighting it to show a larger preview shows the same line.
In JetBrains IDEs the Powerline Symbols are working correctly.
I'm using the releas 1.0.5 on Windows 10

**Comment by philippnurullin** [comment] 2020-04-27 07:35
Hi @OmegaRogue . I believe this is the same problem. https://github.com/JetBrains/JetBrainsMono/issues/189 Will be fixed in 1.0.6 update. We found the cause.

**Closed by philippnurullin** 2020-04-27 07:36 UTC
Labels: duplicate
